### ISSUE TITLE
数据库中间件

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/NyaaCore#26]
NC 作为中间件提供一个抽象的数据库操作接口，对多种数据库提供支持。

插件在调用时通过读取插件自身的数据库类型和配置建立一个数据库连接实例，使用 NC 的抽象方法对数据库连接实例进行 CRUD 操作。

例如插件的配置中：

```
database:
  provider: redis
  connection: username:password@host/db_name
```

* `provider` 需要支持：
  * MySQL/SQLite
  * MongoDB
  * Redis
* `connection` 调用时交由 provider 解析数据库连接信息。
  * `host` 数据库主机
  * `username` 和 `password` 数据库连接信息
  * `db_name` 在不同类型数据库中的作用
    * MySQL/MongoDB 中代表数据库的名称
    * Redis 中代表 key 前缀 `nyaa_p1:plugin_func2:some_data`

- [ ] SQLite 支持
- [ ] MySQL 支持
- [ ] MongoDB 支持
- [ ] Redis 支持
- [ ] 抽象类中间件
- [ ] 容错检查和测试例
- [ ] 文档
- [ ] 数据迁移工具

其他需要注意的？

**Comment by Librazy** [comment]
Available at maven-repo-dev and 4.2 releases

**Comment by Librazy** [comment]
# Mysql
Mysql database.
``` yaml
database:
  provider: mysql
  connection:
    autoscan: true
    url: jdbc:MySQL://localhost:3306/heh
    username: username
    password: password
# 'package' and 'jdbc' are optional
    package: cat.nyaa.HamsterEcoHelper.utils.database.tables 
    jdbc: com.mysql.jdbc.Driver
```
or select table classes manually
``` yaml
database:
  provider: mysql
  connection:
    autoscan: false
    url: jdbc:MySQL://localhost:3306/heh
    username: root
    password: root
    tables:
    - cat.nyaa.HamsterEcoHelper.utils.database.tables.TempStorageRepo
    - cat.nyaa.HamsterEcoHelper.utils.database.tables.MarketItem
    - cat.nyaa.HamsterEcoHelper.utils.database.tables.ItemLog
    - cat.nyaa.HamsterEcoHelper.utils.database.tables.signshop.SignShop
    - cat.nyaa.HamsterEcoHelper.utils.database.tables.signshop.Sign
    - cat.nyaa.HamsterEcoHelper.utils.database.tables.signshop.ShopStorageLocation
    - cat.nyaa.HamsterEcoHelper.utils.database.tables.signshop.LottoStorageLocation
# 'jdbc' is optional
    jdbc: com.mysql.jdbc.Driver
```
# Sqlite
Sqlite database.
```
database:
    provider: sqlite
    connection:
        autoscan: true
        file: HamsterEcoHelper.db
# 'package' is optional
        package: cat.nyaa.HamsterEcoHelper.utils.database.tables
```
# Map
Java collection Map. No configuration is available. Not persisted and will be cleared when restart/reload.
```
database:
    provider: map
    connection: []
```
